version: '3.2'

networks:
  app-network:
    driver: bridge

volumes:
  pg-data:
  home-dir:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/app:cached
      - home-dir:/home/user:cached
    ports:
      - '4001:8080'
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: 'forge'
      POSTGRES_USER: 'forge'
      POSTGRES_PASSWORD: 'forge'
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
    ports:
      - 5432
      - '4005:5432' # Port 4005 for connecting from localhost
    networks:
      - app-network
