name: build

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  phpunit:
    name: Run phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master # Action page: <https://github.com/shivammathur/setup-php>
        with:
          php-version: 7.3

      - name: Install Composer 'hirak/prestissimo' package
        run: composer global require hirak/prestissimo --update-no-dev

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-suggest

      - name: Execute phpunit
        run: composer phpunit
